# Use root/example as user/password credentials
version: '3.8'

services:
  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      # <Port exposed> : < Postgres Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
    volumes:
      # Where our data will be persisted
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: akin/blog-backend
    build:
      context: ../blog-be
      dockerfile: Dockerfile
    depends_on:
      # Our app does not work without our database
      # so this ensures our database is loaded first
      - database
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database


      # docker-compose down

      # Delete all containers using the following command:
      # docker rm -f $(docker ps -a -q)

      # Delete all volumes using the following command:
      # docker volume rm $(docker volume ls -q)

      # Restart the containers using the following command:
      # docker-compose up -d
